ecommerce/shopproject/cart_app/urls.py
from django.urls import path
from .import views
app_name='cart_app'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_delete,name='full_delete')
]

ecommerce/shopproject/search_app/urls.py
from django.urls import path
from .import views

app_name='search_app'
urlpatterns=[
     path('',views.searchResult,name='searchResult')

]

ecommerce/shopproject/shopapp/urls.py
from django.urls import path

from shopapp import views
app_name='shopapp'
urlpatterns = [

    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail')
]

ecommerce/shopproject/shopproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from shopproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shopapp.urls')),
    path('search/',include('search_app.urls')),
    path('cart_app/',include('cart_app.urls')),
]
if settings.DEBUG:
         urlpatterns += static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
         urlpatterns += static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)

ecommerce/shopproject/cart_app/models.py
from django.db import models
from shopapp.models import product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
         db_table='Cart'
         ordering=['date_added']
    def __str__(self):
              return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce/shopproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/shopproject/shopapp/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    img=models.ImageField(upload_to='category',blank=True)


    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shopapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    img=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateField(auto_now_add=True)
    update=models.DateField(auto_now=True)

    def get_url(self):
        return reverse('shopapp:prodCatdetail',args=[self.category.slug,self.slug])


    class Meta:
        ordering = ('name',)
        verbose_name ='product'
        verbose_name_plural ='products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/shopproject/cart_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shopapp.models import product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    products=product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
             cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=products,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
           cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
              product=products,
              quantity=1,
               cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
      try:
            cart=Cart.objects.get(cart_id=_cart_id(request))
            cart_items=CartItem.objects.filter(cart=cart,active=True)
            for cart_item in cart_items:
                 total+=(cart_item.product.price * cart_item.quantity)
                 counter +=cart_item.quantity

      except ObjectDoesNotExist:
               pass
      return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
      cart=Cart.objects.get(cart_id=_cart_id(request))
      productt=get_object_or_404(product,id=product_id)
      cart_item=CartItem.objects.get(product=productt,cart=cart)
      if cart_item.quantity >1:
           cart_item.quantity -=1
           cart_item.save()
      else:
           cart_item.delete()
      return redirect('cart_app:cart_detail')

def full_delete(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    productt = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=productt, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommerce/shopproject/search_app/views.py
from django.shortcuts import render
from shopapp.models import product
from django.db.models import Q
# Create your views here.

def searchResult(request):
     products=None
     query=None
     if 'q' in request.GET:
         query=request.GET.get('q')
         products=product.objects.all().filter(Q(name__contains=query)  |  Q(description__contains=query))
         return render(request,'search.html' ,{'query':query,'products':products})

ecommerce/shopproject/shopapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import category,product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def allProdCat(request, c_slug=None):
    c_page=None
    products_List=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_List=product.objects.all().filter(category=c_page,available=True)
    else:
          products_List=product.objects.all().filter(available=True)
    paginator=Paginator(products_List,4)
    try:
          page=int(request.GET.get('page','1'))
    except:
              page=1
    try:
         products=paginator.page(page)
    except  (EmptyPage,InvalidPage):
         products=paginator.page(Paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})


def proDetail(request,c_slug,product_slug):
    try:
          productt=product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,"product.html",{'product':productt})

ecommerce/shopproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
     <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}" >
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="d-flex flex-column min-vh-100">
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js'  %}"></script>
<script src="{% static 'js/bootstrap.min.js'  %}"></script>

</body>
</html>

ecommerce/shopproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   this is the cart page proceed to review your items and place the order
{% endblock %}
{% block title %}
Cart-ABC company PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
               Your Shopping Cart is Empty
        </h1>
        <br>
           <p class="text-center">
            please click <a href="{% url 'shopapp:allProdCat' %}">Here  continue shopping.</a>
           </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
</div>
<div class="row mx_auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
         <table class="table my_custom-table">
             <thead class="my_custom_thead">
              <tr>
                  <th colspan="5">
                       Your Items
                  </th>
              </tr>
             </thead>
             <tbody>
             {% for cart_item in cart_items %}
             <tr>
                 <td>
                     <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" alt=""  style="width:100px; height:100px;" class="float-left rounded custom_image"></a>
                 </td>
                 <td class="text-left">
                     {{cart_item.product.name}}
                     <br>
                     SKU: {{cart_item.product.id}}
                     <br>
                     price: $ {{cart_item.product.price}}
                     <br>
                        Qty: {{cart_item.quantity}}  x ${{cart_item}}
                 </td>
                 <td>
                     $ {{cart_item.sub_total}}
                 </td>
                 {% if cart_item.quantity <  cart_item.product.stock %}
                 <td>
                      <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa fa-plus-circle custom_icon"></i></a>
                     &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-circle custom_icon"></i></a>
                     &nbsp;<a href="{% url 'cart_app:full_delete' cart_item.product_id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                 </td>
                 {% else %}
                 <td>
                      &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus-circle custom_icon" ></i></a>
                      &nbsp; <a href="{% url 'cart_app:full_delete' cart_item.product_id %}" class="custom_a"><i class="fa fa-trash custom_icon" ></i></a>
                 </td>
                 {% endif %}
             </tr>
             {% endfor %}
             </tbody>

         </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                checkout
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                please review your shopping cart items before proceeding with the order payment
            </td>
        </tr>
        </tbody>
    </table>
    <div class="mx-auto">
        <a href="{% url 'shopapp:allProdCat' %}" class="btn btn_secondary btn-block my_custom_button">continue To shop</a>
    </div>

</div>

</div>
{% endif %}
</div>
{% endblock %}

ecommerce/shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {% if category %}
       {{category.description|truncatewords:155}}
  {% else %}
         <p> welcome to EMK mall, Here you can buys different items....</p>
  {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
      {{category.name}} - EMK MALL
   {% else %}
         See our new amazing collections -emk mall
  {% endif %}
{% endblock %}
{% block content %}
      {% if category %}
          <div>
                <div class="row my_row_class">
                      <div class="mx_auto">
                           <P><a href="{% url 'shopapp:allProdCat'  %}">our product collections</a></P>
                </div>
                    </div>
          </div>
      {% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}">

</div>
<br>
<div>
                   <h1><b><u><i>{{category.name}}</i></u></b></h1>
                       <p>{{category.description}}</p>
 </div>
{% else %}
<div>
   <img class="my image" src="{% static 'img/banner.jpg' %}" alt="our product" width="1350" height="550">
</div>
<br>
<div>
    <h1><b><u>Our products collections</u></b></h1>
    <p>You can click on the ‘item to generate’ column and select the format you want content in.

Below that, you can select if you want an HTML tag in your content or not After that, you can choose how many paragraphs you want in the ‘how many items to generate’ column.Then, yoFinally, click on the button ‘generate’</p>
</div>
        {% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-3">
                <div class="card text-center" style="min-width:18rem;" width=200px height=150px>
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src ="{{product.img.url}}" alt="{{product.name}}" width="350px" height="200px"></a>
                    <div class="card-body">
                     <h3><u>{{product.name}}</u></h3>
                        <p>{{product.price}}</p>
                    </div>
                </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

ecommerce/shopproject/templates/footer.html
<footer class="mt-auto">
  <div class="footer navbar-fixed-bottom my-footer">
  <p class="text-center">&copy; EMK mall,we can shop anytime</p>
</div>
</footer>

ecommerce/shopproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'shopapp:allProdCat' %}"></a><img src="{% static 'img/logo.png' %}" alt="logoimage" width="400px">
    </center>
</header>

ecommerce/shopproject/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shopapp:allProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart_app:cart_detail' %}"><i class="fa fa-shopping-cart" >({{item_count}})</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="GET">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search" ></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/shopproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     {{product.description|truncatewords:155}}

{% endblock %}
{% block title %}
       {% if category %}
            {{product.name}}


       {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
     <div class="mx_auto">
         <p> <a href="{% url 'shopapp:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>{{product.name}}</p>
     </div>
</div>
<div class="container">
<br>
<div class="row">
       <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width-18rem">
                      <img src="{{product.img.url}}" alt="{{product.name}}" width="350" height="250">
                </div>
       </div>

                <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                    <div>
                    <h1 class="my-prod-title">{{product.name}}</h1>
                    <p>${{product.price}}</p>
                    <p>About product</p>
                    <p class="text-justify my_prod_text">{{product.description}}</p>
                  {% if product.stock <= 0 %}
                 <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
                  {% else %}
                   <a class="btn btn_secondary" href="{% url 'cart_app:add_cart' product.id  %}">Add to Cart</a>
                   {% endif %}
                </div>
         </div>
    </div>
</div>








{% endblock %}

ecommerce/shopproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

           We have variety of  items...Just Search It.
{% endblock %}
{% block title %}
 search
{% endblock %}
{% block content %}
<div>
<p class="text-center my_search_text">You have search for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-3">
                <div class="card text-center" style="min-width:18rem;" width=200px height=150px>
                    <a href="{{product.get_url}}"><img class="card-img-top my_image" src ="{{product.img.url}}" alt="{{product.name}}" width="350px" height="200px"></a>
                    <div class="card-body">
                     <h3><u>{{product.name}}</u></h3>
                        <p>{{product.price}}</p>
                    </div>
                </div>
        </div>
       {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> o result found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}